version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
    # If you want to persist the data between runs, uncomment the volumes section
    # below and replace HOST-DIR with a path on your host that docker can access
    # and mount as a volume.
    #volumes:
    #  - HOST-DIR:/usr/share/elasticsearch/data
  toxcast-importer:
    build: ./importer
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCHHOSTNAME: elasticsearch
  toxcast-api:
    build: ./api
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      ELASTICSEARCHHOSTNAME: elasticsearch
